defines/constants.sv
defines/csr.sv
defines/op.sv
defines/instruction.sv
defines/pipeline_status.sv
defines/forwarding.sv
defines/branch_pred_pkg.sv
lib/wishbone/wishbone_test.sv
lib/wishbone/wishbone_timer.sv
lib/wishbone/wishbone_buttons.sv
lib/wishbone/wishbone_ram.sv
lib/wishbone/wishbone_interconnect.sv
lib/synchronizer.sv
rtl/dyn_branch_pred.sv
rtl/fetch_stage.sv
rtl/register_file.sv
rtl/instruction_decoder.sv
rtl/decode_stage.sv
rtl/execute_stage.sv
rtl/memory_stage.sv
rtl/csr_file.sv
rtl/writeback_stage.sv
rtl/Hadi_V.sv
rtl/icarus_soc.sv
